services:
  php:
    image: example_php
    build: build/php
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - "80:80" 
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: test
      DB_USER: test
      DB_PASS: test
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 60s

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: test
      PMA_PASSWORD: test
    depends_on:
      database:
        condition: service_healthy

  cron:
    build:
      context: .
      dockerfile: ./build/cron/Dockerfile
    depends_on:
      database:
        condition: service_healthy
      php:
        condition: service_started
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    environment:
      TZ: Europe/Prague
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: test
      DB_USER: test
      DB_PASS: test
    entrypoint: ["/bin/sh","-c"]
    command: >
      echo '* * * * * cd /var/www/html && php bin/console.php app:embeddings >> /proc/1/fd/1 2>&1' > /etc/crontabs/app
      && crond -f -l 8
    restart: unless-stopped

  embeddings:
    image: python:3.11-slim
    working_dir: /var/www/html/embedding/server
    volumes:
      - ../:/var/www/html
    command: >
      sh -lc "pip install -r requirements.txt && python embeddings_api.py"
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: test
      DB_USER: test
      DB_PASS: test
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"

  migrate:
    image: example_php
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: test
      DB_USER: test
      DB_PASS: test
    depends_on:
      database:
        condition: service_healthy
    command: ["php", "bin/console.php", "migrations:migrate", "--no-interaction", "--allow-no-migration"]
    restart: "no"